# dependabot
# npm ライブラリは週一、GitHub Actions は月一でアップデートを調べる

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    groups:
      update-eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "prettier"
      update-textlint:
        patterns:
          - "textlint"
          - "textlint-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule: 
      interval: "monthly"
