# タグ「n版」または「n版m刷」（たとえば「初版」、「初版2刷」や「第二版一刷」など）をプッシュすると、
# 電子版および印刷入稿用 PDF を添付したリリースが作成されます。
#
# [未対応内容]
# - 電子版 PDF は本文のみで、表紙画像の結合は未対応です。
# - 表紙データ PSD など、その他のファイルはリリースを編集して、追加してください。

name: Publish and Release PDF

on:
  push:
    tags:
      - '*版'
      - '*版*刷'

permissions:
  contents: write

jobs:
  publish-and-release-pdf:
    name: Publish and Release PDF
    runs-on: ubuntu-latest

    # 環境変数を定義する
    env:
      # 生成される PDF のパス
      EBOOK_PDF_PATH: ./book/output/ebook.pdf
      EBOOK_COVERED_PDF_PATH: ./book/output/ebook_covered.pdf
      PRESS_PDF_PATH: ./book/output/press.pdf
      COVER_PNG_PATH: ./book/cover/cover.png
      COVER_PSD_PATH: ./book/cover/*.psd
    
    steps:
      # フォントをキャッシュ&リストアする
      - name: Restore or Save Cache Font Noto
        id: cache-font-noto
        uses: actions/cache@v4
        with:
          path: /usr/share/fonts/opentype/noto
          key: font-noto-cache-key

      # 日本語をインストールする
      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
        if: ${{ steps.cache-font-noto.outputs.cache-hit != 'true' }}
      
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      
      # PDFを作成する
      - name: make PDF
        run: |
          corepack enable
          yarn install --frozen-lockfile
          
          yarn build
          if [ ! -f "${EBOOK_PDF_PATH}" ]; then
            echo "エラー: 電子版 PDF の生成に失敗しました。"
            exit 1
          fi

          yarn cover
          if [ ! -f "${EBOOK_COVERED_PDF_PATH}" ]; then
            echo "ワーニング: 電子版 PDF の表紙付けがされていません。"
          fi

          make pdf_press
          if [ ! -f "${PRESS_PDF_PATH}" ]; then
            echo "エラー: 印刷入稿用 PDF の生成に失敗しました。"
            exit 1
          fi
          
      # リリースの作成
      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: false
          files: |
            ${{ env.EBOOK_PDF_PATH }}
            ${{ env.EBOOK_COVERED_PDF_PATH }}
            ${{ env.PRESS_PDF_PATH }}
            ${{ env.COVER_PNG_PATH }}
            ${{ env.COVER_PSD_PATH }}
